### ISSUE TITLE
"Logger" builtin middleware

### ISSUE THREAD

**Issue by yusukebe** [yusukebe/hono#11]
We want to have "Logger" middleware as a *builtin* middleware. We have to write middleware with no dependency on any other npm modules. To know how to write middleware, see `Powered By` middleware: 

```js
const poweredBy = async (c, next) => {
 await next()
 await c.res.headers.append('X-Powered-By', 'Hono')
}
```

* <https://github.com/yusukebe/hono/blob/master/src/middleware/poweredBy.js>

After we wrote middleware, add the method to `Middleware` object:

```js
Middleware.poweredBy = poweredBy
```

* <https://github.com/yusukebe/hono/blob/master/src/middleware.js>

And then, we can use middleware like this:

```js
const { Hono, Middleware } = require('hono')
...
app.use('*', Middleware.poweredBy)
```

**Comment by yusukebe** [comment]
Hey @metrue 

Now, the API for builtin middleware is fixed. We want to have "Logger" as builtin middleware. Do you want to write it?

**Comment by metrue** [comment]
@yusukebe happy to.
