### ISSUE TITLE
Best way to set CORS

### ISSUE THREAD

**Issue by jdcauley** [yusukebe/hono#129]
Is there a best way to set Cors in Hono?

**Comment by metrue** [comment]
You can do it with `core` with Hono builtin midlleware like this.
```javascript
import { cors } from 'hono/cros'

app.use(
    '/api2/*',
    cors({
      origin: 'http://example.com',
      allowHeaders: ['X-Custom-Header', 'Upgrade-Insecure-Requests'],
      allowMethods: ['POST', 'GET', 'OPTIONS'],
      exposeHeaders: ['Content-Length', 'X-Kuma-Revision'],
      maxAge: 600,
      credentials: true,
    })
  )
```

**Comment by yusukebe** [comment]
Hi @jdcauley !

Has it been resolved?

**Comment by jdcauley** [comment]
My apologies, I dug into the source and found the cors middleware later in that day.

There were other factors in my set up that were breaking things.

This is resolved.

**Comment by yusukebe** [comment]
All right, thank you!
