### ISSUE TITLE
Argument of type "Handler<string>" is not assignable to parameter of type "Handler<never>" 

### ISSUE THREAD

**Issue by thgick** [yusukebe/hono#133]
TS tells the following error:

Argument of type "Handler<string>" is not assignable to parameter of type "Handler<never>" 
Types of parameters 'string' and 'never' are incompatible. ts(2345)

in 
examples/blog/src/index.ts 

for all routes (get,post,,put,delete) like:
app.get('/', Controller.root)

**Comment by yusukebe** [comment]
Hi @thgick 

I fixed this issue by #134 . Please upgrade `hono` to v0.5.4.
And, the examples are updated. See: <https://github.com/yusukebe/hono/tree/master/examples/blog>

Thank you!

**Comment by thgick** [comment]
Hi @yusukebe!

Great! It works! 
Thank you very much for that quick fix.
