### ISSUE TITLE
@types/service-worker-mock out of date and no longer maintained.

### ISSUE THREAD

**Issue by metrue** [yusukebe/hono#40]
Currently, `hono` depends on `@types/service-worker-mock` to run unit test, there're some interfaces missing and I think it would not be fixed since it's  no longer maintained. https://github.com/zackargyle/service-workers 

For example the `reqest.formData()` is [not supported](https://github.com/zackargyle/service-workers/blob/master/packages/service-worker-mock/models/Body.js) currently, which block some unit test for `hono`.

**Comment by yusukebe** [comment]
Hi @metrue 

As far as I know, there are two ways:

* Use `edge-mock` - https://github.com/samuelcolvin/edge-mock
* Use `miniflare Jest Environment` - https://miniflare.dev/testing/jest

`edge-mock` is used in [benchmark/handleEvent](https://github.com/yusukebe/hono/blob/master/benchmark/handleEvent/index.js). `miniflare Jest Environment` is used in [example/blog](https://github.com/yusukebe/hono/tree/master/example/blog)

I tried both to test with `FormData`. `minflare` is better than `edge-mock`. `miniflare` reproduces Cloudflare Workers API faithfully. This tests will be passed:

```ts
  describe('FormData', () => {
    it('formData - application/x-www-form-urlencoded', async () => {
      app.post('/', async (c) => {
        const form = await c.req.formData()
        // console.log(c.req.headers.get('Content-Type'))
        // => application/x-www-form-urlencoded;charset=UTF-
        return c.text((form.get('aaa') || '').toString())
      })
      const searchParams = new URLSearchParams()
      searchParams.append('aaa', 'bbb')
      const req = new Request('https://localhost/', {
        method: 'POST',
        body: searchParams,
      })
      const res = await app.dispatch(req)
      expect(res.status).toBe(200)
      expect(await res.text()).toBe('bbb')
    })

    it('formData - multipart/form-data', async () => {
      app.post('/', async (c) => {
        const form = await c.req.formData()
        // console.log(c.req.headers.get('Content-Type'))
        // multipart/form-data; boundary=----formdata-undici-0.12093121571495491
        return c.text((form.get('aaa') || '').toString())
      })
      const formData = new FormData()
      formData.append('aaa', 'bbb')
      const req = new Request('https://localhost/', {
        method: 'POST',
        body: formData,
      })
      const res = await app.dispatch(req)
      expect(res.status).toBe(200)
      expect(await res.text()).toBe('bbb')
    })
  })
})
```

And, `miniflare Jest Environment` provides *Environment*. No need to call a method like `makeServiceWorkerEnv()`.

Unfortunately, miniflare dump warning messages, but it will be resolved in the near future.

```
(node:73360) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(node:73360) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
```

I think `miniflare Jest Environment` is best. How about you?

**Comment by metrue** [comment]
Yes,  `miniflare Jest Environment` is better, let's go with it.
