### ISSUE TITLE
default or wildcard route

### ISSUE THREAD

**Issue by justinnoel** [yusukebe/hono#50]
Is there any way to create a default or wildcard route? For example, if I want to build a custom 404 handler, I can't seem to be able to do it.

Example I ***thought*** would work:

```
app.get("/api/abc", handleAbcRoute);
app.get("/api/*", handleCustom404);
```

However, the last wildcard route always takes precedence. There seems to be no way for the first route to be handled appropriately and all other routes use the `handleCustom404` function.

**Comment by yusukebe** [comment]
Hi @justinnoel 
Yes, I think what you are saying is right. So, I've implemented "default route with wildcard" in #52 
Your code and example below will work. 

https://github.com/yusukebe/hono/blob/98924ce16498a118687414b192c1d5769ab62f2c/example/basic/index.js#L88-L91

I released latest version as v0.0.15 by npm registry. You can try if you upgrade Hono.

**Comment by justinnoel** [comment]
Trying it right now with just upgrading to Hone 0.0.15. Getting this:

`Invalid state: ReadableStream is locked`

This is coming from Miniflare (2.0.0). I'm going to try to resolve this and then confirm for you that the default routing is working properly.

**Comment by yusukebe** [comment]
Hi @justinnoel !

I fixed bugs about `ReadableStream is locked` error by this PR. #55 
Now, Hono 0.0.16 is released. Please try it.

**Comment by justinnoel** [comment]
Woohoo 🥳! That definitely fixed the ReadableStream bug.

I've confirmed the default route feature addition is working perfectly.

Thanks so much for your amazing support!
