### ISSUE TITLE
Add example with Miniflare/Wrangler2

### ISSUE THREAD

**Issue by justinnoel** [yusukebe/hono#54]
I'd love to see an official example with Miniflare with live reloading for development mode.

I've put together my own project that was working with Miniflare 2.0.0 and Hono 0.0.13. However, if I update Miniflare to 2.2.0, it no longer works. Miniflare shows this on the durable object example:

```sh
[mf:err] GET /api/: TypeError: Failed to parse URL from [object Object]
    at new Request (/Users/jn/Apps/project-api/node_modules/undici/lib/fetch/request.js:83:23)
    at new Request (/Users/jn/Apps/project-api/node_modules/miniflare/node_modules/@miniflare/core/src/standards/http.ts:398:13)
    at EventTarget.dispatchFetch (/Users/jn/Apps/project-api/node_modules/miniflare/node_modules/@miniflare/core/src/index.ts:999:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server.<anonymous> (/Users/jn/Apps/project-api/node_modules/@miniflare/http-server/src/index.ts:167:20)
```

**Comment by justinnoel** [comment]
Actually, maybe not necessarily Miniflare but the new Wrangler2 `wrangler@beta`?

**Comment by yusukebe** [comment]
Hi @justinnoel 

I've tried a Durable Object example with Miniflare 2.2.0. It worked correctly.
Example is here: <https://github.com/yusukebe/hono/tree/master/example/durable-objects>
This code is based on [the official example](https://github.com/cloudflare/durable-objects-template). It might be well if you use latest version of Hono. If it does not work, let's think about it together.

**Comment by justinnoel** [comment]
Thanks for the response. That's the sample I was using. 

On previous versions of Hono with Miniflare 2.2.0, I was getting the error above.  Now, with Hono 0.0.16, it's all resolved 🎉!

So, something in #55 probably fixed this issue.

Thanks again!

**Comment by MatteoGauthier** [comment]
Got the same `▲ [WARNING] Failed to get worker definitions TypeError: fetch failed` issue with Workers KV on the 3.1.0 version

**Comment by yusukebe** [comment]
Hi @MatteoGauthier !

Could you provide some snippets to reproduce the problem?

I've tried to run the simple application using KV with v3.1.0. It works well.

```ts
import { Hono } from 'hono'

type Bindings = {
  FOO: KVNamespace
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/', async (c) => {
  await c.env.FOO.put('name', 'Hono')
  const val = await c.env.FOO.get('name')
  return c.text(`Hello ${val}`)
})

export default app
```

**Comment by MatteoGauthier** [comment]
> Hi @MatteoGauthier !
> 
> Could you provide some snippets to reproduce the problem?
> 
> I've tried to run the simple application using KV with v3.1.0. It works well.
> 
> ```ts
> import { Hono } from 'hono'
> 
> type Bindings = {
>   FOO: KVNamespace
> }
> 
> const app = new Hono<{ Bindings: Bindings }>()
> 
> app.get('/', async (c) => {
>   await c.env.FOO.put('name', 'Hono')
>   const val = await c.env.FOO.get('name')
>   return c.text(`Hello ${val}`)
> })
> 
> export default app
> ```

Oh sorry, here is a reproduction repository for the issue : https://github.com/MatteoGauthier/hono-fetch-issue-kv

**Comment by yusukebe** [comment]
Thanks! I'll try it.

**Comment by yusukebe** [comment]
I see. But I can't seem to reproduce the issue. Hmm.
